### ISSUE TITLE
autoconf fails

### ISSUE THREAD

**Issue by PAStheLoD** [sjvermeu/cvechecker#1]
Hello!

I've tried to use CVEchecker some time ago, and I decided to try it again, but using the development version (just git clone-ing from the repo) goes nowhere.

If I just run autoconf (2.69 on a Debian Squeeze) it gives the following error:

```
configure.ac:3: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:27: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:52: error: possibly undefined macro: AM_CONDITIONAL
```

If I try `aclocal ; autoheader ; automake --add-missing ; autoconf`, it succeeds, but then I can't use even sqlite3 (and MYSQL is commented out in the src/Makefile, but uncommenting it changes nothing) backend.

So, would you mind updating the documentation? Thanks!

**Comment by cwarner-mdsol** [comment]
This should be remedied with the latest updates as we auto default to sqlite3 now.

**Comment by wudidong** [comment]
config.status: error: cannot find input file: `Makefile.in'

**Comment by sjvermeu** [comment]
Run **autoreconf --force --install** prior to the **./configure** steps.
