### ISSUE TITLE
pullcves pull don't import anything (v3.7 and master)

### ISSUE THREAD

**Issue by zanettea** [sjvermeu/cvechecker#24]
The following scanf call fails on any valid input and database is not filled without reporting any error

`sscanf(bufferptr, "[^:]%s", field, &pos)`

Moreover gcc (4.8) complains:

`gcc -DHAVE_CONFIG_H -I. -I..  -D_USE_SQLITE3    -g -O2   -MT cvecheck.o -MD -MP -MF $depbase.Tpo -c -o cvecheck.o cvecheck.c &&\
mv -f $depbase.Tpo $depbase.Po
cvecheck.c: In function ‘load_cve’:
cvecheck.c:1362:28: warning: too many arguments for format [-Wformat-extra-args]
   while (sscanf(bufferptr, "[^:]%s", field, &pos) == 1) {`

**Comment by sjvermeu** [comment]
Yes, the "too many arguments" I got as well with -Wall -Werror, that one should be fixed.
I'm going to look into the database filling issue...

**Comment by sjvermeu** [comment]
Took me far too long to fix it :-( Current master should be ok. I'll do some more testing this week (I assumed that the pullcves correctly reported that all entries were already in the database when I initially validated).

**Comment by sjvermeu** [comment]
Should be fixed in the 3.8 release.
