### ISSUE TITLE
"git push" missing

### ISSUE THREAD

**Issue by DerDakon** [sjvermeu/cvechecker#27]
It looks like release "3.8" is newer than the current master. Also it would be helpful if the releases could be tagged so that they are easier identifiable in git.

**Comment by sjvermeu** [comment]
Indeed, my bad. It was still in the cleanup branch. It's pushed now. I'll see if I can use the github releases in the future (which uses tags as well).

**Comment by DerDakon** [comment]
You just need to tag the relevant commits and push those to Github so they show up in the webinterface and clones.
