### ISSUE TITLE
No package 'libconfig' found

### ISSUE THREAD

**Issue by littleheary** [sjvermeu/cvechecker#31]
当我安装的时候，提示
No package 'libconfig' found

当我运行
apt-get install libconfig8-dev的时候，又提示
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
您也许需要运行“apt --fix-broken install”来修正上面的错误。
下列软件包有未满足的依赖关系：
 libconfig8-dev : 依赖: libconfig-dev 但是它将不会被安装
 python-webkit : 依赖: libpango1.0-0 (>= 1.14.0) 但是它将不会被安装
 python-webkit-dev : 依赖: python-gtk2-dev 但是它将不会被安装
E: 有未能满足的依赖关系。请尝试不指明软件包的名字来运行“apt --fix-broken install”(也可以指定一个解决办法)。

安装不成功，怎么办？

**Comment by qinyan1007** [comment]
你要安装libconfig-devel包
