### ISSUE TITLE
how to disable sqllite3

### ISSUE THREAD

**Issue by smallfish01** [sjvermeu/cvechecker#32]
Hi, I just install cvechecker and got error:
# ./configure  --enable-mysql-server
checking pkg-config is at least version 0.9.0... yes
checking for CONFIG... yes
checking for SQLITE3... no
configure: error: Package requirements (sqlite3 >= 3.6.16) were not met:

No package 'sqlite3' found.

How can I disable sqlist3 check?

Thank you.

**Comment by sjvermeu** [comment]
Hi smallfish01,

You can disable checking for SQLite3 with the --disable-sqlite3 option to the configure step.

Wkr,
  Sven Vermeulen

**Comment by smallfish01** [comment]
It's ok, I have installed Cvechecker, many thank you!
And now I have another questions, how can I use Cvechecker to check remote server?

Thank you.

**Comment by sjvermeu** [comment]
With cvechecker you can't check a remote server without deployment of cvechecker. It needs to be run on the server that you want to validate. However, with MySQL support, you can have multiple systems run cvechecker and have the data stored in a central database. The tool will use the hostname (by default) as the differentiating name between the different servers (but this is configurable).

I don't recommend having a MySQL "exposed" widely just for this though. The central database approach was meant to be used in a data center context (trusted network).

Wkr,
  Sven Vermeulen

**Comment by sjvermeu** [comment]
Closing issue
