### ISSUE TITLE
cvechecker deafult password

### ISSUE THREAD

**Issue by KnownAsDon** [sjvermeu/cvechecker#33]
I just installed blackarch tools on vanilla arch using strap...and on the packages cvechecker was included.After the sucessful installation(after some strugless) I noticed that a new user was created called svechecker. Now i tried the password root, blackarch, cvechecker and my deafult user password and none of them worked.If anyone could help me I would greatly appreciate it.

**Comment by sjvermeu** [comment]
Hi KnownAsDon,

The account is meant to be a system account, not an interactive one. It is used to run cvechecker in batches (like in cron) with a non-privileged user (as there is no need for cvechecker to have elevated privileges). Generally, this does not require knowledge of any password, and in most cases there is no active password set anyway (but this depends on the distribution and how cvechecker was installed).

**Comment by KnownAsDon** [comment]
Thanks for the info @sjvermeu

**Comment by sjvermeu** [comment]
Your welcome.
