### ISSUE TITLE
Centos6.10 installation is not successful

### ISSUE THREAD

**Issue by wjcgy** [sjvermeu/cvechecker#38]
[root@localhost cvechecker-master]# ./configure --enable-sqlite3
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking Determining host operating system... Linux
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking argp.h usability... yes
checking argp.h presence... yes
checking for argp.h... yes
checking for regcomp... yes
checking for strchr... yes
checking for strrchr... yes
checking for strstr... yes
checking for size_t... yes
configure: WARNING: Please make sure pkg-config is installed and autoreconf run
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for CONFIG... yes
checking for SQLITE3... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in'

**Comment by sjvermeu** [comment]
Hi wjcgy,

If you run "autoreconf --force --install" prior to running the ./configure one, this should generate the necessary files.

Wkr,
  Sven Vermeulen
