### ISSUE TITLE
SSHD detection is not supported

### ISSUE THREAD

**Issue by lflish** [sjvermeu/cvechecker#42]
I feel SSHD is an important service, but this tool does not test it。
Or maybe I'm using it the wrong way？
my sshd is in /usr/bin/sshd

**Comment by sjvermeu** [comment]
We / I only need to add the right rule in the version.dat file, then any
pullvces run will download an updated version of that file and use it in
the next inventory run.

If you have a suggested value I'll happily add it to it.

Wkr,
  Sven

**Comment by lflish** [comment]
I think```,sshd,1,sshd,([0-9]\.[0-9]+)p1,a,gnu,sshd,\1,,,  ```is OK，
this result
```- Found match for /usr/bin/sshd:	cpe:/a:gnu:sshd:7.4:::```

 thanks !!!
