### ISSUE TITLE
Database type "mysql/sqlite" is not supported

### ISSUE THREAD

**Issue by nikhilgeo** [sjvermeu/cvechecker#43]
I have both mysql and sqlite installed in my machine (Ubuntu server 18.04)
```
~/cvechecker/cvechecker-3.9$ sqlite3 --version
3.22.0 2018-01-22 18:45:57 0c55d179733b46d8d0ba4d88e01a25e10677046ee3da1d5b1581e86726f2alt1
~/cvechecker/cvechecker-3.9$ mysql --version
mysql  Ver 14.14 Distrib 5.7.26, for Linux (x86_64) using  EditLine wrapper
```
Running `cvechecker -i` no mater what `dbtype` I configure in `/usr/local/etc/cvechecker.conf` it returns error:
```
~/cvechecker/cvechecker-3.9$ cvechecker -i
Database type "mysql" is not supported.
~/cvechecker/cvechecker-3.9$ cvechecker -i
Database type "sqlite" is not supported.
```

Any idea why this happens, any pointer ?

**Comment by sjvermeu** [comment]
Has cvechecker been built with support for MySQL or SQLite? They're
build-time options (--enable-sqlite3 and --enable-mysql).

**Comment by nikhilgeo** [comment]
My bad, missed it ! I think I have to rebuild, any option to do with out rebuild ?

**Comment by sjvermeu** [comment]
Sadly no, enabling the functionality is only code-wise implemented
modularly. It will require rebuilds.

**Comment by nikhilgeo** [comment]
Got it thanks ! Closing this issue.
