### ISSUE TITLE
ebuild for 4.0

### ISSUE THREAD

**Issue by emcek** [sjvermeu/cvechecker#52]
As you wrote [here](https://github.com/sjvermeu/cvechecker/wiki/Installation):
> ...so I suggest you just take the app-admin/cvechecker and put it in your own overlay  

But there is only ebuild for **3.5** and live version use old deperched **git-2** eclass

**Comment by sjvermeu** [comment]
Sorry about that. I've committed the 4.0 ebuild.

**Comment by emcek** [comment]
I use ebuild for 4.0, and it worked. Just one minor complain:
```
 * The ebuild is installing to one or more unexpected paths:
 * 
 *   /usr/share/doc/cvechecker
 * 
 * Please fix the ebuild to use correct FHS/Gentoo policy paths.
```
