### ISSUE TITLE
Cannot figure, why a modification in `configure.ac` isn't populated into cvechecker

### ISSUE THREAD

**Issue by HenrikBach1** [sjvermeu/cvechecker#59]
Hi

I cannot figure, why the modification in `configure.ac`:

```
AC_INIT([cvechecker], [4.0-modified], [sven.vermeulen@siphos.be])
```
isn't reflected in the build:
```
root@973091faf51e:/projects/cvechecker/cvechecker-2021-05-08-build/cvechecker-master# ./src/cvechecker --version
Database type "sqlite" is not supported.
cvechecker 4.0
root@973091faf51e:/projects/cvechecker/cvechecker-2021-05-08-build/cvechecker-master# 
```
even though its *.c and *.h files are populated with the `autoreconf` command:

![Screenshot from 2021-06-04 16-32-37](https://user-images.githubusercontent.com/10473382/120818130-9ef86080-c552-11eb-9caf-12a8bccb67b8.png)

Thank you

**Comment by sjvermeu** [comment]
Hi Henrik

The version information from the build tools isn't used. The version is hardcoded in the cvecheck.h header file. I wasn't even aware the build tools could handle it (autoconf and automake never became good friends of mine).

Wkr,
  Sven

**Comment by HenrikBach1** [comment]
Hi Sven

Me neither. But I can see, that it is fairly simple and tested it. I'll send a patch in the form of a PR, later.

Thank you.
